# Generated by Django 3.2.9 on 2021-11-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogapp', '0002_rename_publish_date_post_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta_usuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('respuesta', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
    ]
